{
	"version": 1585150917,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/tilemap.png",
		"images/door_closed-sheet0.png",
		"images/door_open-sheet0.png",
		"images/gate_vertical-sheet0.png",
		"images/tile-sheet0.png",
		"images/tile2-sheet0.png",
		"images/tile2-sheet1.png",
		"images/tile2-sheet2.png",
		"images/tile3-sheet0.png",
		"images/tile4-sheet0.png",
		"images/tile5-sheet0.png",
		"images/tile6-sheet0.png",
		"images/action-sheet0.png",
		"images/sofabig-sheet0.png",
		"images/sofasmall-sheet0.png",
		"images/bed-sheet0.png",
		"images/locker-sheet0.png",
		"images/kitchen-sheet0.png",
		"images/kitchen2-sheet0.png",
		"images/kitchen3-sheet0.png",
		"images/kitchen4-sheet0.png",
		"images/table-sheet0.png",
		"images/tablechair-sheet0.png",
		"images/player-sheet0.png",
		"images/solidtile.png",
		"images/dog-sheet0.png",
		"images/dog-sheet1.png",
		"images/dog-sheet2.png",
		"images/randomdirectionpng-sheet0.png",
		"images/spritefont3.png",
		"images/levelcomplsprite-sheet0.png",
		"images/window-sheet0.png",
		"images/complete-sheet0.png",
		"images/restart-sheet0.png",
		"images/restart-sheet1.png",
		"images/complete2-sheet0.png",
		"images/popupbg.png",
		"images/flatdark-sheet0.png",
		"images/flatdark2-sheet0.png",
		"images/flatdark3-sheet0.png",
		"images/flatdark4-sheet0.png",
		"images/hbd-sheet0.png",
		"images/set1_background-sheet0.png",
		"images/set1_tiles-sheet0.png",
		"images/set1_hills-sheet0.png",
		"images/desktop-sheet0.png",
		"images/gray-sheet0.png",
		"media/collect key.m4a",
		"media/collect key.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}